name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - name: Verify build
        run: |
          echo "Checking critical files..."
          test -f client/src/utils/payout.js && echo "Payout util exists"
          test -f .env.example && echo "Env template exists"
